version: "3.8"

tasks:
  git-reset-head-to-last-index:
    cmds:
      - git reset HEAD~
  add-hook-to-git-repo:
    cmds:
      - 'powershell -Command "cd .git/hooks; New-Item -Path . -Name \"prepare-commit-msg\" -ItemType \"file\" "'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''#!/bin/bash''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''# Get the commit message from the argument''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''MSG=\$1''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''# Read the commit message from the file''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''# MSG=$(cat "$MSG_FILE")''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''# Check if the commit message ends with the desired pattern''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''if ! grep -qE \"by [a-zA-Z0-9_]+\$\" $MSG; then''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''  echo \"Your message should ends with \" by [commit_author_name]\" \"''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''  exit 1''"'
      - 'powershell -Command "cd .git/hooks; Add-Content -Path \"prepare-commit-msg\" -Value ''fi''"'
  git-add-files-to-git-index:
    cmds:
      - git add *
  git-commit-without-rule:
    cmds:
      - git commit -m "any commit message goes here"
  git-commit-following-rule:
    cmds:
      - 'git commit -m ''feature: creating hook blocking commits without author name by Matheus Pimentel'''
  git-tag-v1:
    cmds:
      - 'git tag v1.0.0'
  git-tag-list:
    cmds:
      - 'git tag -l'
  git-status:
    cmds: 
      - 'git status'